# Generated by Django 5.1.15 on 2026-02-18 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], db_index=True, default='sandbox', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('user', 'name', 'environment')},
        ),
    ]
