# Generated by Django 5.1.15 on 2026-02-18 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_unique_together_event_environment_and_more'),
        ('integrations', '0002_alter_sesintegration_unique_together_and_more'),
        ('logs', '0001_initial'),
        ('templates_app', '0002_alter_emailtemplate_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], db_index=True, default='sandbox', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', 'environment', '-sent_at'], name='logs_emaill_user_id_df2e46_idx'),
        ),
    ]
